### ISSUE TITLE
这该怎么编译？

### ISSUE THREAD

**Issue by satgo1546** [IcebergThings/ASM76#1]
过了一年，已经完全不知道这编译系统怎么用了。

这个项目理论上不需要使用任何库，所以编译系统大概可以简单些。

要不就做个统一的Makefile如何？

**Comment by satgo1546** [comment]
糟糕，glm还在dependency里，要不干脆把76-Vector也一起扔了如何233

**Comment by bobcao3** [comment]
觉得76 vector可以用别的实现……先扔了吧2333

**Comment by satgo1546** [comment]
OK已经扔掉了
现在这个构建系统就好用了，即使是在Windoge上也蛮好
没有外部deps的世界真舒服233
